### ISSUE TITLE
Unify 3rd party connection to the cart

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#618]
## Issue Name
Unify 3rd party connection to the cart

### Summary
The idea here is to have a standard scenario for events which can be attached to the scicat cart.

There should be a configuration file which specifies what actions are available.

All actions will be added to the jobs table in the mongo database, which is where all information about the files/datasets involved is stored.

When the button is clicked, one of 3 things will happen,
1. A rabbitMQ message is sent out to a specified Queue with the jobID as a parameter
2. The button redirects to a specified URL with the jobID as a parameter
3. Nothing, this is for systems that like to poll, for example an archiver which only runs at midnight or something.

When the 3rd part tool updates things, it should update the status as it is doing things.

**Comment by nitrosx** [comment]
Cart actions should be defined in configuration. 
The entry defining each actions should be an array with multiple instances of the following json entry:
```
 {
  id: '<action_unique_identifier>',
  machine_name: '<action_unique_name>',
  common_name: '<user_friendly_name>',
  icon: '<icon_file_path>',
  type: '<type_of_the_action>',
  <action_specific_keys> : '<action_specific_values>'
 }
```

**Comment by nitrosx** [comment]
If we would like to define the following actions:

1. Archive: submit a message to rabbitmq server rabbit.our.institution on topic **archive**
2. Retrieve: submit a message to rabbitmq server rabbit.our.institution on topic **retrieve**
3. Get Notebook: redirect user to external microservice with URL notebook.our.institution that prepopulate a jupyter notebook and push it to the user machine using http download
4. Analyze: just create a job with the analysis request. An external service will query at scheduled time for this jobs to start the analysis on an external infrastructure 

In order to define such actions, the backend configuration file should contains the following section:
```
cart_actions : [
 {
  id: 'a5f43a5e-26e3-11ee-870c-3b096f8c3106',
  machine_name: 'archive_job_1',
  common_name: 'Archive',
  icon: 'icons/archive.png',
  type: 'rabbitmq',
  server: 'rabbit.our.institution',
  topic: 'archive',
 },
 {
  id: '02999218-26e4-11ee-8bef-7324e23d8360',
  machine_name: 'retrieve_job_1',
  common_name: 'Retrieve',
  icon: 'icons/retrieve.png',
  type: 'rabbitmq',
  server: 'rabbit.our.institution',
  topic: 'retrieve',
 },
 {
  id: '15ea1338-26e4-11ee-a932-d77973d535cb',
  machine_name: 'jupyter_job_1',
  common_name: 'Get Notebook',
  icon: 'icons/notebook.png',
  type: 'redirect',
  server: 'notebook.our.institution',
 },
 {
  id: '15ea1338-26e4-11ee-a932-d77973d535cb',
  machine_name: 'analysis_job_1',
  common_name: 'Run analysis',
  icon: 'icons/analysis.png',
  type: 'no_action',
  parameter_1: 'value_1',
  ...
 }
]
```

**Comment by nitrosx** [comment]
After meeting with @bolmsten, we should introduce the concept of action which can be performed on cart or datasets.
Action can trigger job creation or call an external URL.
More details coming

**Comment by nitrosx** [comment]
Also this requires more effort, so I am assigning it to its own release.

**Comment by nitrosx** [comment]
Super seeded by issues #635
