### ISSUE TITLE
Jobs migration: controller file

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/backend#625]
### Summary
Refactor Jobs controller including swagger decorators

**Comment by sbliven** [comment]
Is this done now? If not, can someone add more information?

**Comment by despadam** [comment]
Most of it is done - it is covered by #838 , #839, #840. Plus we need one additional PR for minor fixes.
I will close this one once the above are complete and we clean up the file, because it still contains a lot of commented out code from the previous version that we need to decide if it stays or not.

**Comment by despadam** [comment]
TODO: the commented out code will be ~~covered in a validate action~~ --> reintroduced in the controller

**Comment by despadam** [comment]
Why is `checkDatasetFiles` only used for public jobs?

**Comment by despadam** [comment]
Should we enforce job types like so?
```
export enum JobType {
  Archive = "archive",
  Retrieve = "retrieve",
  Public = "public",
}
```
